### PR TITLE
Update to .NET 8

### PR DESCRIPTION
**Pull request by marcel-tatasteel**
## Types of changes
- [ X ] Other (docs, build config, etc)

- Update to .NET 8.0
- Update from 472 => 481

## Checklist:

- [ X ] I've added tests for my code. (most of the time mandatory)

### CODE REVIEW

**Comment by marcel-tatasteel** [comment]
@gasparnagy Could you take a look at this PR?

**Comment by gasparnagy** [comment]
@marcel-tatasteel Thx for the PR. Do you have an idea why the tests fail on the CI? Does those work fine locally?

**Comment by marcel-tatasteel** [comment]
@gasparnagy Locally all tests are green, seems like something in the build pipeline broke. (previous autobot updates also fail)

**Comment by marcel-tatasteel** [comment]
@gasparnagy Locally test now also fail because of an update of nUnit to 4.0.0 which does not support net45 anymore. 

-> error: Could not find a part of the path 'C:\Users\AppData\Local\Temp\DeveroomTest\DS_Gen875le_2.4.1_nunit_1194832604\packages\NUnit.4.0.0\lib\net45'. (2,1s)

**Comment by gasparnagy** [comment]
@marcel-tatasteel if you check back the stacktrace, you can maybe find the code that uses "net45" now for the path, you can change that to anything that is supported now with nunit. Let's see

**Comment by marcel-tatasteel** [comment]
@gasparnagy Will try to fix the tests

**Comment by marcel-tatasteel** [comment]
@gasparnagy Because the 'ApprovalTest' updates nUnit to 4.0.0, all nUnit approval test <net461 or <net60 will fail. See changelog nUnit:
Supported platforms:
      - .NET Framework 4.6.2+
      - .NET 6.0+ 

3 options => 
1. force nUnit 3 for older frameworks
2. Drop testsupport for older versions and only approval test for net462+ and net6.0+ 
3. Use nUnit 3 for older frameworks and use nunit 4 for newer..... 

Let met know.

**Comment by gasparnagy** [comment]
@marcel-tatasteel I guess option 1) suppose to be "force nUnit **4** for older frameworks" or was it "force nUnit 3 for **newer** frameworks"?

**Comment by mountain65** [comment]
Personally I love moving forward, so I would choose option 2).
But I can imagine that you look at that differently as OS project manager.

**Comment by gasparnagy** [comment]
@marcel-tatasteel Thank you very much! Great work!

I try to somehow arrange with Tricentis that it get's released ASAP.

**Comment by gasparnagy** [comment]
Fixes #145

**Comment by gasparnagy** [comment]
Until it will be published to the marketplace, you can install this version from the VSIX file attached to the release: https://github.com/SpecFlowOSS/SpecFlow.VS/releases/tag/v2022.1.93-net8

**Comment by gasparnagy** [comment]
@vjagwani-nc Use the Reqnroll extension instead. It works with SpecFlow too. https://marketplace.visualstudio.com/items?itemName=Reqnroll.ReqnrollForVisualStudio2022

**Pull request merged**
