### PR TITLE
Added templates

### PR DESCRIPTION
**Pull request by marcosikkens**
I added feature file templates for Dutch, French and German to the project. This is my first time doing this actually so i hope i'm doing the correct stuff.

### CODE REVIEW

**Comment by SabotageAndi** [comment]
Thx. I will try it out in the next days.

**Comment by SabotageAndi** [comment]
@gasparnagy can you have a look at this?

**Comment by gasparnagy** [comment]
Having multiple item templates for the same is quite annoying. The plan is (was) to have a single template, but fill it with the keywords configured for SpecFlow.
So I would not merge this PR now. 
@marcosikkens, if you would be interested to contribute in the "dynamic" template solution please let me know and I will help to kick it off.

**Comment by gabcen** [comment]
Can we add the SpecFlow Step Definition template?

**Comment by gasparnagy** [comment]
@gabcen Could you please create a separate issue for that, so we can better dicuss?

**Pull request closed without merging**
